name = "my-worker"
main = "src/index.js"
compatibility_date = "2022-05-21"
account_id = "1f7a19ae429ecdc5820f1f32c9245c9f"
workers_dev = true

[env.production]
workers_dev = false
route = "https://my-first-cloudflare-worker.simongreen.dev/"